version: "3.8"

services:
  stock_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_app_container
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
